### ISSUE TITLE
broker's disk is full, write to logic queue error

### ISSUE THREAD

**Issue by KBCode** [apache/rocketmq#4826] opened 2022-08-16 02:46 UTC
rocketmq version 4.9.4
 I encountered this error during the pressure test. Check that there is still a lot of free space on the broker disk. 
The remaining space of the four master disks is sufficient .  no slave

broker error log:
the message store is not writable. It may be caused by one of the following reasons: the broker's disk is full, write to logic queue error, write to index file error, etc .
 
data store path /app/

[xx rocketmqlogs]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.5G     0  7.5G   0% /dev
tmpfs           7.6G  2.5M  7.5G   1% /dev/shm
tmpfs           7.6G  476K  7.6G   1% /run
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
/dev/vda1        50G  3.3G   44G   7% /
/dev/vdb        1.0T  377G  648G  37% /app
 
client log:
` 
2022-08-16 09:46:31,256 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: {} mq producer  error : test-topic-qq-181Send [3] times, still failed, cost [23]ms, Topic: test-topic-qq-181, BrokersSent: [broker-a, broker-b, broker-a]
See http://rocketmq.apache.org/docs/faq/ for further details.
org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [23]ms, Topic: test-topic-qq-181, BrokersSent: [broker-a, broker-b, broker-a]
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:664) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1342) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1288) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:324) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at com.xx.xx.producer(xx.java:63) ~[bprofile-test-1.0.0-SNAPSHOT.jar:?]
	at com.xx.xx.runTest(xx.java:44) ~[bprofile-test-1.0.0-SNAPSHOT.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_192]
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL:  0.37 CQ:  0.37 INDEX:  0.37], messages are put to the slave, message store has been shut down, etc.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:709) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:505) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:487) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:431) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:853) ~[rocketmq-client-4.6.1.jar:4.6.1]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:583) ~[rocketmq-client-4.6.1.jar:4.6.1]
`

**Comment by duhenglucky** [comment] 2022-08-17 01:51
> 

It seems that the error is caused by the message being sent to the slave node.

**Comment by lizhanhui** [comment] 2022-08-17 01:55
> It seems that the error is caused by the message being sent to the slave node.

@duhengforever How do you jump to this conclusion as he explicitly stated there is no slave node in his deployment?

**Comment by lizhanhui** [comment] 2022-08-17 02:00
@KBCode I suggest you to query brokerConfig first using admin toolset to ensure data are stored in the partition you assume.  Is it possible someone else changed your clustser config without notice? Say, flagging your node as read-only node, changing the directory permission mode,  etc.

**Comment by KBCode** [comment] 2022-08-18 02:29
> 

No one modified it. It is strange that the same error occurred on four master servers at the same time.

Later after deleting stored, the pressure test again did not reproduce this problem.

**Comment by lizhanhui** [comment] 2022-08-23 11:04
@KBCode I'd close this issue as it seems not reproducible. Feel free to reopen it if you run into this issue again.

**Closed by lizhanhui** 2022-08-23 11:04 UTC
Labels: type/question
