### ISSUE TITLE
ext fields not signed in client side

### ISSUE THREAD

**Issue by mrttx** [apache/rocketmq#1216] opened 2019-05-22 05:18 UTC
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- query msg by unique key failed (org.apache.rocketmq.tools.admin.DefaultMQAdminExt#viewMessage(java.lang.String, java.lang.String))
- remoting.log:
2019-05-22 12:41:06 ERROR QueryMessageThread_7 - process request exception
org.apache.rocketmq.acl.common.AclException: Check signature failed for accessKey=ADMIN_1
	at org.apache.rocketmq.acl.plain.PlainPermissionLoader.validate(PlainPermissionLoader.java:210) ~[rocketmq-acl-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.acl.plain.PlainAccessValidator.validate(PlainAccessValidator.java:132) ~[rocketmq-acl-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.BrokerController$10.doBeforeRequest(BrokerController.java:510) ~[rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.doBeforeRpcHooks(NettyRemotingAbstract.java:172) ~[rocketmq-remoting-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:202) ~[rocketmq-remoting-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80) [rocketmq-remoting-4.5.0.jar:4.5.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
2019-05-22 12:41:06 ERROR QueryMessageThread_7 - RemotingCommand [code=12, language=JAVA, version=313, opaque=4, flag(B)=0, remark=null, extFields={_UNIQUE_KEY_QUERY=true, beginTimestamp=1558491696049, Signature=m/iltJe7YXe4KPwDi5rheCjVBYc=, topic=TopicTest, AccessKey=ADMIN_1, maxNum=32, endTimestamp=9223372036854775807, key=AC1B00013FBF18B4AAC26E5EA7990000}, serializeTypeCurrentRPC=JSON]

- client:

![img](https://user-images.githubusercontent.com/24975904/58148894-2556e800-7c93-11e9-8d8a-c0a6a96b07c4.png)

2. Please tell us about your environment:
- RocketMQ 4.5.0
- aclEnable=true
- JDK 1.8
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhenglucky** [comment] 2019-05-23 01:09
@zongtanghu Cloud you help solve this problem? it seems that it indeed is an issue caused by ACL. Thanks.

**Comment by zongtanghu** [comment] 2019-05-23 01:30
Hi @mrttx  ,can I join you in dingding talk or wechart?

**Comment by mrttx** [comment] 2019-05-23 02:00
微信吧, weixin94086824  @zongtanghu

**Comment by vongosling** [comment] 2019-05-23 02:57
@mrttx could you post your details here instead of weichat. I think more committers and contributor could help you.

**Comment by mrttx** [comment] 2019-05-23 05:36
I have captured the args of org.apache.rocketmq.acl.common.AclUtils#combineRequestContent in the broker by arthas:
![broker](https://user-images.githubusercontent.com/24975904/58225046-cd7fb600-7d52-11e9-9d6d-7460972c10a8.png)

I think the problem is:
when viewMessage by unique key
   1) before acl rpc hook invoked(org.apache.rocketmq.client.impl.MQClientAPIImpl#queryMessage):
```
    public void queryMessage(
        final String addr,
        final QueryMessageRequestHeader requestHeader,
        final long timeoutMillis,
        final InvokeCallback invokeCallback,
        final Boolean isUnqiueKey
    ) throws RemotingException, MQBrokerException, InterruptedException {
        RemotingCommand request = RemotingCommand.createRequestCommand(RequestCode.QUERY_MESSAGE, requestHeader);
        request.addExtField(MixAll.UNIQUE_MSG_QUERY_FLAG, isUnqiueKey.toString());
        this.remotingClient.invokeAsync(MixAll.brokerVIPChannel(this.clientConfig.isVipChannelEnabled(), addr), request, timeoutMillis,
            invokeCallback);
    }
```
   2) when invoke acl rpc hook and before writeAndFlush request(org.apache.rocketmq.remoting.protocol.RemotingCommand#headerEncode), acl rpc hook only uses the fields of custom request headers
   3) when verify signature in the broker, broker uses the ext fields of request

I have tried to fix it, test in my environment and create a PR #1219, is there any problem?

**Comment by zongtanghu** [comment] 2019-05-23 05:42
Okay,we will verify your issue in our local enviroment.And then I will look at your pr's code.Thanks for your issue and pr's code. @mrttx

**Comment by duhenglucky** [comment] 2020-03-12 08:41
@zongtanghu ping

**Comment by zongtanghu** [comment] 2020-03-20 15:21
Okay, I will check this issue and pr in next week, and solve it as soon as possible, @duhenglucky @vongosling

**Comment by zhangjidi2016** [comment] 2020-03-23 02:27
This problem of query msg by unique key failed I have resloved in this pr([#1756](https://github.com/apache/rocketmq/pull/1756)), my way is filter out the UNIQUE_MSG_QUERY_FLAG attribute when constructing the authentication content to compute the signature in broker.

**Comment by zongtanghu** [comment] 2020-03-23 02:35
Hi  @duhenglucky, out team member have already put forward a pr which has already been merged.

**Comment by duhenglucky** [comment] 2020-03-23 02:39
@mrttx this [issue](https://github.com/apache/rocketmq/pull/1756) has been fixed, It is recommended to update the latest version, and more verification results are welcome.

**Closed by duhenglucky** 2020-03-23 02:39 UTC
Labels: enhancement, question
