### ISSUE TITLE
Executing `nohup sh bin/mqnamesrv &` will block

### ISSUE THREAD

**Issue by startjava** [apache/rocketmq#2099] opened 2020-06-16 23:39 UTC
root@ghy-VirtualBox:/home/ghy/T/rocketmq-all-4.7.0-bin-release# nohup sh bin/mqnamesrv &
[1] 7722
root@ghy-VirtualBox:/home/ghy/T/rocketmq-all-4.7.0-bin-release# nohup: 忽略输入并把输出追加到'nohup.out'
呈阻塞状态，除非按ctrl+c结束

这个问题在网上有很多人遇到，请问官方这个问题到底应该如何解决?是什么根本原因导致的，感谢。
还是这个问题就是正常的，输出“nohup: 忽略输入并把输出追加到'nohup.out'”并呈阻塞状态是正常的，感谢。

**Comment by imaffe** [comment] 2020-06-17 01:52
Yes I agree we do need to precisely define whether we should block after rocketmq startup. @ShannonDing probably we should mark this as a question or enhancement ~

**Comment by imaffe** [comment] 2020-06-17 02:45
I investigated the problem, I think it is not blocked, but some stdout issue.

The line you saw n`ohup: 忽略输入并把输出追加到'nohup.out'` is not blocking, but overwriting your next prompt line..

When you see
![image](https://user-images.githubusercontent.com/22848576/84849076-21102080-b087-11ea-82f4-9d593fc7d5b6.png)

It is not blocking, and you can type commands like `ls`, and it goes like

![image](https://user-images.githubusercontent.com/22848576/84849115-34bb8700-b087-11ea-9b4c-d16643c2143b.png)

So this is just some weird bash overwriting problem, it looks like blocked but actually not. When you press Ctrl+C it just create a new prompt line for you.

BTW, could you do me a favor providing me a link  where people discuss this problem as you mentioned you saw a lot of discussions , maybe we can answer this question once and for all？ Thanks

**Comment by imaffe** [comment] 2020-06-17 14:06
Will close this issue as this is not a bug recorder. We recommend use dev maillist for questions and use github issues only for bug recording purposes.

**Closed** 2020-06-17 14:07 UTC
Labels: question
