### ISSUE TITLE
Why does rocketmq generate nohup.out and log files?

### ISSUE THREAD

**Issue by startjava** [apache/rocketmq#2101] opened 2020-06-17 00:46 UTC
只用log不可以吗？？nohup.out为什么要创建？这两者有什么区别呢？

**Comment by startjava** [comment] 2020-06-17 00:51
如果搭建集群，所有的实例都向同一个nohup.out文件输出？内容是不是会出现混乱？感谢，如何避免呢?

**Comment by imaffe** [comment] 2020-06-17 01:35
IMHO， nohup.out stores low-value log outputs (stdout). Usually developers would use logs only for debugging purposes, but maybe in some extreme cases developers might want to use nohup.out to debug.

> 如果搭建集群，所有的实例都向同一个nohup.out文件输出？内容是不是会出现混乱？感谢，如何避免呢?

I'm not sure what would happen here, but I  would assume in cluster mode, each node would output to the nohup.out on each node instead of printing to one nohup.out. (Like nohup.out would be local to each node). But I'm not sure about this.



Even if they output to one nohu[.out file (which is unlikely), because we rarely use it to debug, it is acceptable. On the other hand, because we are not sure if developers will use nohup.out or not, we decide to keep it just in case.

**Comment by dominicqi** [comment] 2020-06-17 02:09
> 只用log不可以吗？？nohup.out为什么要创建？这两者有什么区别呢？

nohup.out is the nohup command default stdout output file. you can redirect to `/dev/null` . `nohup xxxx  >/dev/null`

**Comment by imaffe** [comment] 2020-06-17 02:12
> > 只用log不可以吗？？nohup.out为什么要创建？这两者有什么区别呢？
> 
> nohup.out is the nohup command default stdout output file. you can redirect to `/dev/null` . `nohup xxxx >/dev/null`

Yeah, users can decide to mute the nohup output if they want, rocketmq choose to keep it by default and users can choose to keep it or not.

**Comment by imaffe** [comment] 2020-06-17 14:06
Will close this issue as this is not a bug recorder. We recommend use dev maillist for questions and use github issues only for bug recording purposes.

**Closed** 2020-06-17 14:07 UTC
Labels: question
