### ISSUE TITLE
[Enhancement] Version 5.0 of docker supports amd64

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#6847] opened 2023-06-01 11:32 UTC
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

![image](https://github.com/apache/rocketmq/assets/42484192/57cfe2bc-e00d-4c07-a03a-d9a7dfe67c5e)
Version 5.0 of docker only has ppc64le

### Motivation

Version 5.0 of docker supports amd64

### Describe the Solution You'd Like

Version 5.0 of docker supports amd64

### Describe Alternatives You've Considered

no

**Comment by wu-sheng** [comment] 2023-06-01 13:07
The PR is blocked by SkyWalking CI, due to we can't verify RocketMQ plugin of tracing. The root cause seems no server image support.

Could anyone point out the reason?

**Comment by caigy** [comment] 2023-06-06 03:43
Let me have a look. It seems something is wrong with the images.

**Comment by caigy** [comment] 2023-06-07 11:49
@weihubeats @wu-sheng The images have been fixed with correct amd64 architecture, please check if it helps. Sorry for any inconvenience.
![image](https://github.com/apache/rocketmq/assets/17410645/5b34ae5b-0522-4da0-954c-6db7d61bf72f)

**Closed** 2023-06-08 01:33 UTC
Labels: type/enhancement
