### ISSUE TITLE
MappedFile shutdown problem

### ISSUE THREAD

**Issue by lebron374** [apache/rocketmq#2094] opened 2020-06-14 11:57 UTC
MappedFile destroy will invoke ReferenceResource shutdown method,
some confusion about refCount?
 
 this.refCount.set(-1000 - this.getRefCount())

should replace by 

 this.refCount.set(-1000 + this.getRefCount());

i think the purpose is every time decreate by 1000 until 0

```
public abstract class ReferenceResource {

    protected final AtomicLong refCount = new AtomicLong(1);
    protected volatile boolean available = true;
    protected volatile boolean cleanupOver = false;
    private volatile long firstShutdownTimestamp = 0;

    public synchronized boolean hold() {
        if (this.isAvailable()) {
            if (this.refCount.getAndIncrement() > 0) {
                return true;
            } else {
                this.refCount.getAndDecrement();
            }
        }

        return false;
    }

    public boolean isAvailable() {
        return this.available;
    }

    public void shutdown(final long intervalForcibly) {
        if (this.available) {
            this.available = false;
            this.firstShutdownTimestamp = System.currentTimeMillis();
            this.release();
        } else if (this.getRefCount() > 0) {
            if ((System.currentTimeMillis() - this.firstShutdownTimestamp) >= intervalForcibly) {
                // some confusion here
                this.refCount.set(-1000 - this.getRefCount());
                this.release();
            }
        }
    }
```

**Comment by imaffe** [comment] 2020-06-17 02:16
I think here( -1000 - this.getRefCount()) probably means : it just want to set the refCount to a negative value indicating a  shutdown. (-1000) is just a "negative enough" number that guarantees the result (-1000 - this.getRefCount()) will always be negative. How do you think ?

**Comment by imaffe** [comment] 2020-06-17 14:05
Will close this issue as this is not a bug recorder. We recommend use dev maillist for questions and use  github issues only for bug recording purposes.

**Closed** 2020-06-17 14:05 UTC
Labels: question
