### ISSUE TITLE
Transactional Message 

### ISSUE THREAD

**Issue by dominicqi** [apache/rocketmq#2098] opened 2020-06-16 06:32 UTC
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
`transientStorePoolEnable = true` and send TransactionalMessage 

- What did you expect to see?

- What did you see instead?
The EndTransactionThread never check ok but error in store.log .
> 2020-06-16 13:54:26 WARN EndTransactionThread_7 - selectMappedBuffer request pos invalid, request pos: 6110, size: 4, fileFromOffset: 0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

I see broker if  transactionalMessage  need check will put a new half message ,then  check producer ,
If check success result to broker ,but transientStorePool not  do commit yet. (the max interval like 400ms ?) then this error will happen,  did  i misreading  the document ?  TransactionMessage should not work with `transientStorePoolEnable` and 'async_flush'?

**Comment by imaffe** [comment] 2020-06-17 02:25
Sorry but maybe it would be helpful for us to investigate if you can provide more detailed description （can be in English or Chinese）of the bug , like steps to reproduce, expected behaviour.

**Comment by imaffe** [comment] 2020-06-21 04:49
Sorry we're closing this issue because it doesn't contain enough information for us to investigate the problem, if you'd like to investigate further, could you please provide a fresh new issue with a more detailed description and a minimal test case to reproduce the issue ? Thanks~

**Closed** 2020-06-22 01:44 UTC
Labels: question
