### ISSUE TITLE
NettyRemotingAbstract.invokeAsyncImpl() a suggestion about callback ResponseFuture

### ISSUE THREAD

**Issue by 17683908932** [apache/rocketmq#2251] opened 2020-08-13 18:32 UTC
channel.writeAndFlush(request).addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture f) throws Exception {
                        if (f.isSuccess()) {
                            responseFuture.setSendRequestOK(true);
                            return;
                        }
                        requestFail(opaque);
                        log.warn("send a request command to channel <{}> failed.", RemotingHelper.parseChannelRemoteAddr(channel));
                    }
                });

question:  the method scanResponseTable() has been callback the responseFuture before f.isSuccess(), scanResponseTable() think the responseFuture is error or timeout, but responseFuture is success.

suggestion: like requestFail(). from responseTable get it

if (f.isSuccess()) {
    responseFuture.setSendRequestOK(true);
    return;
}
replace::
if(f.isSuccess()) {
        ResponseFuture responseFuture = responseTable.get(opaque);
        if (responseFuture != null) {
            responseFuture.setSendRequestOK(true);
       }
}

**Comment by RongtongJin** [comment] 2020-08-14 06:06
setSendRequestOK just confirm that message has been sent out, so I don’t know where the issue is.

**Comment by RongtongJin** [comment] 2020-08-15 06:52
I will close the Issue first, but please feel free to reopen it if you have any other issues.

**Closed by RongtongJin** 2020-08-15 06:52 UTC
Labels: question

**Comment by 17683908932** [comment] 2020-08-16 17:21
NettyRemotingAbstract.processResponseCommand()会向ResponseFuture里面添加response并且回调, 
如果在这之前scanResponseTable已经移除了,  processResponseCommand()就不能向ResponseFuture里面添加response,
 然后ChannelFutureListener会把ResponseFuture.setSendRequestOK设成true, scanResponseTable再执行回调, response 是null, 但是sendRequestOK是true, 就会抛出这个异常MQClientException ex = new MQClientException("unknow reseaon", responseFuture.getCause());
